import { execFileSync } from "node:child_process";
import { prisma } from "./prisma";
import { runHermesTask } from "./hermes-runner";

type ProvisioningInput = {
  budgetCents: number;
  provider: string;
  purpose: string;
  resource: string;
};

const supportedProviders = new Set(["vercel", "neon", "upstash", "generic"]);
const providerServices: Record<string, string> = {
  generic: "vercel/project",
  neon: "neon/postgres",
  upstash: "upstash/redis",
  vercel: "vercel/project",
};

export async function createProvisioningPlan(input: ProvisioningInput) {
  const provider = normalizeProvider(input.provider);
  const budgetCents = normalizeBudget(input.budgetCents);
  const org = await prisma.org.findFirst({
    include: {
      repos: {
        orderBy: {
          createdAt: "asc",
        },
        where: {
          watchedEnabled: true,
        },
      },
    },
    orderBy: {
      createdAt: "asc",
    },
  });

  if (!org) throw new Error("No Ronin org is configured.");

  const repo = org.repos[0] ?? null;
  const id = `provisioning-${Date.now()}`;
  const purpose = input.purpose.trim() || "Provision demo infrastructure for Ronin generated docs and integration work.";
  const resource = input.resource.trim() || defaultResourceForProvider(provider);
  const service = providerServices[provider] ?? providerServices.generic;
  const catalog = getStripeCatalogEvidence(service);
  const command = nextStripeProjectsCommand({ provider, resource });
  const hermes = await runHermesTask({
    cwd: process.cwd(),
    skills: ["ronin", "stripe-projects"],
    prompt: buildProvisioningPrompt({
      budgetCents,
      catalogEvidence: catalog.evidence,
      command,
      provider,
      purpose,
      repo: repo?.fullName,
      resource,
      service,
    }),
    timeoutMs: 180_000,
  });
  const plan = buildPlan({
    budgetCents,
    command,
    hermesOutput: hermes.rawOutput,
    provider,
    purpose,
    repo: repo?.fullName,
    resource,
    runnerBackend: hermes.backend,
    service,
    serviceAvailable: catalog.available,
  });

  const run = await prisma.run.create({
    data: {
      id,
      input: JSON.stringify({
        budgetCents,
        command,
        executionMode: "dry_run_capable_not_executed",
        provider,
        purpose,
        resource,
        runnerBackend: hermes.backend,
        service,
        serviceAvailable: catalog.available,
      }),
      kind: "provisioning.stripe_plan",
      orgId: org.id,
      repoId: repo?.id,
      status: "approval_required",
      summary: `${providerLabel(provider)} provisioning plan generated by Hermes with ${formatUsd(budgetCents)} cap. Execution is disabled.`,
    },
  });

  await prisma.$transaction([
    prisma.artifact.create({
      data: {
        content: plan,
        kind: "stripe_provisioning_plan",
        orgId: org.id,
        repoId: repo?.id,
        runId: run.id,
        title: `${providerLabel(provider)} Provisioning Plan`,
      },
    }),
    prisma.auditLog.create({
      data: {
        action: "provisioning.plan_created",
        actorType: "ronin",
        metadata: JSON.stringify({
          budgetCents,
          command,
          executionMode: "dry_run_capable_not_executed",
          provider,
          resource,
          runnerBackend: hermes.backend,
          service,
          serviceAvailable: catalog.available,
        }),
        orgId: org.id,
        repoId: repo?.id,
        runId: run.id,
        target: provider,
      },
    }),
  ]);

  return prisma.run.findUnique({
    include: {
      artifacts: {
        orderBy: {
          createdAt: "desc",
        },
      },
      repo: true,
    },
    where: {
      id: run.id,
    },
  });
}

export async function approveLatestProvisioningPlan() {
  const run = await prisma.run.findFirst({
    include: {
      org: true,
      repo: true,
    },
    orderBy: {
      createdAt: "desc",
    },
    where: {
      kind: "provisioning.stripe_plan",
      status: "approval_required",
    },
  });

  if (!run) throw new Error("No provisioning plan is awaiting approval.");

  const input = parseInput(run.input);
  const approval = buildApprovalRecord(input);

  await prisma.$transaction([
    prisma.artifact.create({
      data: {
        content: approval,
        kind: "stripe_provisioning_approval",
        orgId: run.orgId,
        repoId: run.repoId,
        runId: run.id,
        title: "Budget Approval Recorded",
      },
    }),
    prisma.run.update({
      data: {
        completedAt: new Date(),
        output: JSON.stringify({
          approvedAt: new Date().toISOString(),
          executionMode: "approval_recorded_no_resource_created",
          nextCommand: nextStripeProjectsCommand(input),
        }),
        status: "approved",
        summary: `${providerLabel(input.provider)} provisioning approved with ${formatUsd(input.budgetCents)} cap. No resource was created automatically.`,
      },
      where: {
        id: run.id,
      },
    }),
    prisma.auditLog.create({
      data: {
        action: "provisioning.approved",
        actorType: "operator",
        metadata: JSON.stringify({
          budgetCents: input.budgetCents,
          executionMode: "approval_recorded_no_resource_created",
          provider: input.provider,
          resource: input.resource,
        }),
        orgId: run.orgId,
        repoId: run.repoId,
        runId: run.id,
        target: input.provider,
      },
    }),
  ]);

  return prisma.run.findUnique({
    include: {
      artifacts: {
        orderBy: {
          createdAt: "desc",
        },
      },
      repo: true,
    },
    where: {
      id: run.id,
    },
  });
}

function getStripeCatalogEvidence(service: string) {
  try {
    const catalog = execFileSync("stripe", ["projects", "catalog"], {
      encoding: "utf8",
      maxBuffer: 1024 * 1024,
      stdio: "pipe",
      timeout: 30_000,
    });
    const lines = catalog
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.includes(service));

    return {
      available: lines.length > 0,
      evidence: lines.length ? lines.join("\n") : `Service ${service} was not found in the current Stripe Projects catalog output.`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Stripe Projects catalog failed.";
    return {
      available: false,
      evidence: `Stripe Projects catalog check failed: ${message}`,
    };
  }
}

function buildProvisioningPrompt(input: {
  budgetCents: number;
  catalogEvidence: string;
  command: string;
  provider: string;
  purpose: string;
  repo?: string;
  resource: string;
  service: string;
}) {
  return `Use the Ronin and stripe-projects skills.

Ronin is preparing a gated infrastructure provisioning plan for a protocol/devtool team.

Critical safety rules:
- Dry-run only.
- Do not execute shell commands.
- Do not call Stripe.
- Do not provision resources.
- Do not spend money.
- Do not write files.
- Do not claim anything was created.
- Ronin may validate the Stripe Projects catalog separately. Do not claim that no Stripe API or read-only catalog calls happened globally. Claim only that no provisioning command, provider resource creation, credential write, or spend happened.

Context:
- Repo scope: ${input.repo ?? "org-level"}
- Provider choice: ${providerLabel(input.provider)}
- Stripe Projects service: ${input.service}
- Resource name: ${input.resource}
- Budget cap: ${formatUsd(input.budgetCents)}
- Purpose: ${input.purpose}

Stripe Projects catalog evidence:
${input.catalogEvidence}

Staged command after explicit approval:
${input.command}

Return a concise Markdown plan with:
- why this resource is useful
- provider/service
- staged command
- what would be written to .env or .projects
- budget/cost caveats
- risks
- rollback/cleanup command
- explicit statement that nothing was executed`;
}

function buildPlan(input: {
  budgetCents: number;
  command: string;
  hermesOutput: string;
  provider: string;
  purpose: string;
  repo?: string;
  resource: string;
  runnerBackend: string;
  service: string;
  serviceAvailable: boolean;
}) {
  return `# Hermes Stripe Provisioning Plan

Provider: ${providerLabel(input.provider)}
Stripe Projects service: ${input.service}
Resource: ${input.resource}
Budget cap: ${formatUsd(input.budgetCents)}
Repo scope: ${input.repo ?? "org-level"}
Runner backend: ${input.runnerBackend}
Catalog validated: ${input.serviceAvailable ? "yes" : "no"}
Execution mode: dry_run_capable_not_executed

## Purpose

${input.purpose}

## Hermes plan

${sanitizeHermesPlan(input.hermesOutput)}

## Controls

- No provider resource was created.
- No Stripe Projects provisioning command was executed.
- Budget cap is ${formatUsd(input.budgetCents)}.
- Approval is required before any real provisioning.
- Real execution remains disabled unless RONIN_ALLOW_REAL_PROVISIONING=true.
- Credentials must be scoped to this resource and written only to gitignored locations.

## Staged Stripe Projects action

\`\`\`bash
${input.command}
\`\`\`
`;
}

function buildApprovalRecord(input: ProvisioningInput) {
  return `# Provisioning Approval

Approved provider: ${providerLabel(input.provider)}
Approved resource: ${input.resource}
Budget cap: ${formatUsd(input.budgetCents)}
Staged command: ${nextStripeProjectsCommand(input)}

This approval records operator consent for a future Stripe Projects provisioning action. Ronin did not create a real provider resource automatically in this local demo path.

Execution mode: approval_recorded_execution_disabled

Next command:

\`\`\`text
${nextStripeProjectsCommand(input)}
\`\`\`
`;
}

function nextStripeProjectsCommand(input: Pick<ProvisioningInput, "provider" | "resource">) {
  const provider = normalizeProvider(input.provider);
  const service = providerServices[provider] ?? providerServices.generic;
  return `stripe projects add ${service} --name ${shellSafeName(input.resource)} --json`;
}

function parseInput(value: string): ProvisioningInput {
  const parsed = JSON.parse(value) as Partial<ProvisioningInput>;
  return {
    budgetCents: normalizeBudget(parsed.budgetCents ?? 500),
    provider: normalizeProvider(parsed.provider ?? "vercel"),
    purpose: parsed.purpose?.trim() || "Provision demo infrastructure.",
    resource: parsed.resource?.trim() || "ronin-demo",
  };
}

function sanitizeHermesPlan(value: string) {
  return value
    .replace(/no Stripe API calls were made/gi, "no Stripe provisioning commands were executed")
    .replace(/no shell commands were run/gi, "no provisioning shell commands were run by Hermes")
    .replace(/no files were written/gi, "no provisioning files or credentials were written");
}

function normalizeBudget(value: number) {
  if (!Number.isFinite(value)) return 500;
  return Math.max(100, Math.min(Math.round(value), 10_000));
}

function normalizeProvider(value: string) {
  const provider = value.trim().toLowerCase();
  return supportedProviders.has(provider) ? provider : "generic";
}

function defaultResourceForProvider(provider: string) {
  if (provider === "vercel") return "Ronin generated docs deployment";
  if (provider === "neon") return "Ronin demo Postgres database";
  if (provider === "upstash") return "Ronin support memory Redis";
  return "Ronin demo dependency";
}

function providerLabel(provider: string) {
  if (provider === "vercel") return "Vercel";
  if (provider === "neon") return "Neon";
  if (provider === "upstash") return "Upstash";
  return "Generic provider";
}

function formatUsd(cents: number) {
  return `$${(cents / 100).toFixed(2)}`;
}

function shellSafeName(value: string) {
  return JSON.stringify(value.replace(/[^\w .-]/g, "").trim() || "ronin-demo");
}
